### ISSUE TITLE
ObjectToMap conversion ignores explicitly transient properties

### ISSUE THREAD

**Issue by olley** [integrity-tf/integrity#109]
The value conversion iterates over all property descriptors the Bean Introspector returns. Even if a field is marked with the keyword "transient" and the corresponding getter is annotated with "java.beans.Transient", the readMethod is invoked and recursively converted.

In our case this leads to an endless loop, because the converted object contains a convenience method to query a referenced object from the server lazily. (Due to the server-client transition the identity check of already visited objects in conversion does not work in this case)

**Comment by S1artie** [comment]
I have changed the behavior of the converter to honor the java.beans.Transient annotation as intended by the bean introspector. Transient properties now will be ignored when converting beans to maps.
