### ISSUE TITLE
java.util.ConcurrentModificationException with list parameters during variable update

### ISSUE THREAD

**Issue by olley** [integrity-tf/integrity#168]
When handing a list as a suite parameter to a nested suite, during variable synchronization a _"com.esotericsoftware.kryo.KryoException: java.util.ConcurrentModificationException"_ occurs while handling the VariableUpdateMessage.
The issue can be reproduced with the follwing script:
```
forkdef myFork
suitedef forkTest with
	suite nestedSuite on myFork
	suite otherSuite aParam: "test", "test"
	suite nestedSuite on myFork
suiteend
suitedef otherSuite gets aParam with
	suite nestedSuite myParam: aParam
suiteend
suitedef nestedSuite gets myParam with
	-- Noop
suiteend
```

**Comment by S1artie** [comment]
Can be reproduced; thanks for the minimal example. Working on a fix.
