### ISSUE TITLE
Add license info to all POMs

### ISSUE THREAD

**Issue by profhenry** [integrity-tf/integrity#204]
It would be nice to add a license info to all POMs.
Especially to the wrapped stuff in the dependency artifacts

**Comment by S1artie** [comment]
All POMs of Integrity modules which are used in a system-under-test context now contain proper license info. Also, starting with the dependencies packaged for the upcoming Integrity 18.0.0 release (sourced from Eclipse 2018-09), all dependencies' POMs will also be generated with the respective license info.
