### ISSUE TITLE
Add a keyboard-shortcut to connect the test runner in the integrity view

### ISSUE THREAD

**Issue by dowei87** [integrity-tf/integrity#227]
When running tests from eclipse it is possible to run the test using a keyboard-shortcut but it is not possible to connect the testrunner in the integrity view. With this it is unfortunatelly not pssoble to control the whole "test-chain" via shortcuts.

**Comment by S1artie** [comment]
Keyboard shortcuts (configurable through normal Eclipse preferences) have been added for the following actions in the Integrity Test Runner view:

- Run selected Integrity test launch config (run chosen config + autoconnect)
- Debug selected Integrity test launch config (same as run, but in debug mode)
- Terminate running Integrity test
- Connect to an already-running Integrity test runner
