### ISSUE TITLE
Catch uncaught exceptions in endpoint communication

### ISSUE THREAD

**Issue by carstenSpraener** [integrity-tf/integrity#258]
The EndpointInputProcessor catches IOExceptions and reports abborting in the finally block. Throwables other than IOExceptions are silently consumed. Please add a "catch(Throwable t)" block to the EndpointInputProcessor.run() mehtod like this:

Eindpoit.java:334
			} catch (IOException exc) {
				// filter out socket closed messages; we're expecting those to happen and they're handled just fine
				if (!"socket closed".equals(exc.getMessage().toLowerCase())) {
					exc.printStackTrace();
				}
			} catch( Throwable t ) {
				t.printStackTrace();
			} finally {
				closeInternal();
				if (listener != null) {
					listener.onConnectionLost(Endpoint.this);
				}
			}

Because this is a Threads run()-Method and so the last instance, a catch of Throwable would be absolutely OK. Otherwise, error situations are hard to discover.

**Comment by S1artie** [comment]
Correct observation, thanks. The suggested change was implemented.
